// Generated by CoffeeScript 1.9.2
(function() {
  var query;

  query = {
    resource: 'Encounter',
    params: [
      'and', {
        param: {
          name: 'name',
          type: 'string'
        },
        element: {
          path: 'Patient.name',
          type: 'HumanName'
        },
        operator: '=',
        value: ['x', 'y']
      }
    ],
    joins: {
      subject: {
        resource: 'Patient',
        on: '???',
        params: [
          'and', {
            param: {
              name: 'name',
              type: 'string'
            },
            element: {
              path: 'Patient.name',
              type: 'HumanName'
            },
            operator: '=',
            value: ['x', 'y'],
            param: {
              name: 'name',
              type: 'string'
            },
            element: {
              path: 'Patient.name',
              type: 'HumanName'
            },
            operator: '=',
            value: ['x', 'y']
          }
        ]
      }
    }
  };

}).call(this);
