// Generated by CoffeeScript 1.9.2
(function() {
  var crud, plv8, test_read;

  plv8 = require('../lib/plv8');

  crud = require('../src/crud');

  test_read = function(res) {
    res = JSON.parse(res);
    return expect(res.resourceType).toEqual('StructureDefinition');
  };

  describe("CRUD", function() {
    it("read", function() {
      var res;
      res = crud.read(plv8, 'StructureDefinition', 'Patient');
      return test_read(res);
    });
    return it("read in db", function() {
      var np, res;
      np = require('../lib/node2pl');
      np.scan('../src/crud');
      res = plv8.execute("select fhir.read('StructureDefinition', 'Patient') as read")[0]['read'];
      return test_read(res);
    });
  });

}).call(this);
